config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount API::Base => '/'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Application::Config.sidekiq_username && password == Application::Config.sidekiq_password
  end

  mount Sidekiq::Web, at: '/sidekiq'
  
  
  get 'account/inactive/:token' => 'user/user#inactive_account'
  
  get 'account/update-password/:token' => 'user/user#update_password'
  put 'account/update-password/:token' => 'user/user#update_password', :as => "update_password"
end

app/models/user.rb
class User < ActiveRecord::Base

  include Accessable

  # soft delete
  acts_as_paranoid

  # add callbacks to generate user's username based on `name`, `first_name` and/or `last_name`
  include UserNamed

  # Basic user validations and setup
  include UserConcerns::Basic
  
  # User auth related setup (authentication, account confirmation, password recovery, account block)
  include UserConcerns::Auth
  
  include UserConcerns::Notifications
  
  include UserConcerns::Discomforts

end

app/controllers/user/user_controller.rb
class User::UserController < ApplicationController
  
  layout 'external_page'
  
  
  def inactive_account
    service = ::Services::V1::Users::InactivateAccountService.new(nil, params)
    service.execute

    if service.success?
      @msg = "sucesso"
    else
      @msg = "erro #{service.full_errors_messages.to_sentence}"
    end
    render 'user/inactivate_account'
  end

  def update_password
    if not params[:password].nil? and not params[:password_confirmation].nil? then
      #altera a senha
      service = ::Services::V1::Auth::PasswordUpdateService.new(nil, params)
      service.execute
     
      if not service.success? then
        @msg = service.full_errors_messages.to_sentence
      else 
        render 'user/update_password_done' and return
      end
    end
    render 'user/update_password'
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/inactivate_account.erb
<div class="row">
	<div class="bg1">
		<img class="resize" src="/img/img_welcome3.png" alt="Image Cow">
	</div>
</div>

<div class="row">
	<div class="col-md-8 col-md-offset-2 text-center">
		<h1 class="animated bounceInDown">Thank you.</h1>
		<p class="animated fadeInUpDelay">
			We're sorry if we have disturbed you and thanks for letting us know.
		</p>
	</div>
</div>

app/views/user/update_password.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2 text-center">
		<p class="animated fadeInUpDelay">
			Just type your new password and we're all set.
		</p>
		<% if defined?(@msg)%>
		<div class=" text-center">
			<h7>
				<%= @msg%>
			</h7>
		</div>
		<%end%>
	</div>
</div>

<%= form_tag(update_password_path(params[:token]), method:'put') do |f| %>
<div class="row">
	<div class="formpass">

		<h3>New Password</h3>
		<br>
		<%= password_field_tag :password, nil, autofocus: true, :class => "w3-input w3-border w3-round", :placeholder => "",  :required => "" %>
		<br>
		<h3> Repeat Password:</h3>
		<br>
		<%= password_field_tag :password_confirmation, nil, autofocus: true, :class => "w3-input w3-border w3-round", :placeholder  => "",  :required => "" %>

	</div>
</div>

<div class="row">
	<div class="col-md-6 col-md-offset-3 text-center">
		<%= submit_tag "Save Password", :class => "get-started-btn btnpadding"%>
	</div>
</div>
<% end %>

app/views/user/update_password_done.erb
<div class="row">
	<div class="text-center done">
		<h9>
			We're all set.
		</h9>
	</div>
</div>